import React, { useState, useEffect, useRef } from "react";
import {
  FiPlus,
  FiSearch,
  FiChevronLeft,
  FiChevronRight,
  FiCalendar,
  FiClock,
  FiZap,
  FiLoader,
  FiX,
  FiSend,
  FiTrash2,
  FiGrid,
  FiList,
  FiRefreshCw,
  FiInstagram,
  FiTwitter,
  FiMenu,
} from "react-icons/fi";

import InstagramIcon from "../assets/instagram.svg";
import LinkedinIcon from "../assets/linkedin.svg";

// ─── Constants ───────────────────────────────────────────────────────────────

const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
const DAY_LABELS_LONG = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];
const DAY_LABELS_SHORT = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

const PLATFORM_META = {
  instagram: {
    label: "Instagram",
    color: "text-pink-400",
    bg: "bg-pink-500/10",
    border: "border-pink-500/20",
    icon: <img src={InstagramIcon} alt="Instagram" className="w-3.5 h-3.5" />,
  },
  linkedin: {
    label: "LinkedIn",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    border: "border-blue-500/20",
    icon: <img src={LinkedinIcon} alt="LinkedIn" className="w-3.5 h-3.5" />,
  },
  twitter: {
    label: "X (Twitter)",
    color: "text-sky-400",
    bg: "bg-sky-500/10",
    border: "border-sky-500/20",
    icon: <FiTwitter className="w-3.5 h-3.5" />,
  },
};

const STATUS_META = {
  scheduled: {
    label: "Scheduled",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/20",
    dot: "bg-amber-400",
  },
  published: {
    label: "Published",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/20",
    dot: "bg-emerald-400",
  },
  draft: {
    label: "Draft",
    color: "text-neutral-400",
    bg: "bg-neutral-700/40",
    border: "border-neutral-700/40",
    dot: "bg-neutral-500",
  },
  autopilot: {
    label: "Autopilot",
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    border: "border-purple-500/20",
    dot: "bg-purple-400",
  },
};

const SEED_POSTS = [
  {
    id: 1,
    title: "Content Hacks to Boost Reach",
    caption:
      "Boost your content reach with these simple hacks! 🚀\n1. Target trending keywords\n2. Hook the user in the first 3 seconds\n#productivity #contentstrategy #growth",
    dateString: "2030-04-08",
    time: "10:00 AM",
    platform: "instagram",
    status: "scheduled",
    category: "Productivity",
    img: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=300&auto=format&fit=crop&q=80",
    isAiAutopilot: false,
  },
  {
    id: 2,
    title: "Introducing Smart Insights Dashboard",
    caption:
      "Our new Smart Insights Dashboard is finally here! 📊\nTrack reach, engagement, and comments in one workspace.\n#analytics #dataviz #marketing",
    dateString: "2030-04-08",
    time: "03:30 PM",
    platform: "linkedin",
    status: "scheduled",
    category: "Product",
    img: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80",
    isAiAutopilot: false,
  },
  {
    id: 3,
    title: "Motivation for Content Creators",
    caption:
      "To all the creators out there: keep showing up! 🌟\nConsistency builds compounding results.\n#motivation #creators #dailygrind",
    dateString: "2030-04-19",
    time: "09:00 AM",
    platform: "instagram",
    status: "scheduled",
    category: "Lifestyle",
    img: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=300&auto=format&fit=crop&q=80",
    isAiAutopilot: false,
  },
  {
    id: 4,
    title: "5 Morning Rituals for a Better Day",
    caption:
      "The first hour of your day sets the tone for everything that follows.\n#wellness #morning #routine",
    dateString: "2030-04-03",
    time: "08:00 AM",
    platform: "instagram",
    status: "published",
    category: "Wellness",
    img: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=300&auto=format&fit=crop&q=80",
    isAiAutopilot: false,
  },
  {
    id: 5,
    title: "AI Autopilot: Growth Hacking (Part 1)",
    caption:
      "Automated post generated by Autopilot. AI Insights suggest peak engagement for instagram.\n#autopilot #aiplanning #growthos",
    dateString: "2030-04-12",
    time: "09:00 AM",
    platform: "instagram",
    status: "autopilot",
    category: "Productivity",
    img: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=300&auto=format&fit=crop&q=80",
    isAiAutopilot: true,
  },
  {
    id: 6,
    title: "Building in Public: Week 4 Update",
    caption:
      "Week 4 of building GrowthOS in public. Here's what shipped, what broke, and what's next.\n#buildinpublic #startup #saas",
    dateString: "2030-04-15",
    time: "11:00 AM",
    platform: "linkedin",
    status: "draft",
    category: "Startup",
    img: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=300&auto=format&fit=crop&q=80",
    isAiAutopilot: false,
  },
  {
    id: 7,
    title: "AI Autopilot: Growth Hacking (Part 2)",
    caption:
      "Continuing our deep-dive into growth hacking frameworks. 3 high-ROI strategies this week.\n#growth #autopilot",
    dateString: "2030-04-22",
    time: "09:00 AM",
    platform: "instagram",
    status: "autopilot",
    category: "Productivity",
    img: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=300&auto=format&fit=crop&q=80",
    isAiAutopilot: true,
  },
  {
    id: 8,
    title: "Scaling Systems Before You Need To",
    caption:
      "Build systems before they're urgent. Automation isn't a shortcut — it's survival.\n#startup #founders #growth",
    dateString: "2030-04-22",
    time: "02:00 PM",
    platform: "linkedin",
    status: "scheduled",
    category: "Startup",
    img: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=300&auto=format&fit=crop&q=80",
    isAiAutopilot: false,
  },
];

const PROMPT_TOPICS = [
  "productivity & focus tips",
  "wellness & mindfulness",
  "startup growth story",
  "product feature spotlight",
  "finance & wealth building",
  "behind the scenes",
];

const IMG_POOL = [
  "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=300&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=300&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=300&auto=format&fit=crop&q=80",
  "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=300&auto=format&fit=crop&q=80",
];

// ─── Micro Badges ─────────────────────────────────────────────────────────────

function PlatformBadge({ platform }) {
  const meta = PLATFORM_META[platform] || PLATFORM_META.instagram;
  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold ${meta.color} ${meta.bg} border ${meta.border}`}
    >
      <span className="w-3 h-3 flex items-center justify-center">
        {meta.icon}
      </span>
      {meta.label}
    </span>
  );
}

function StatusBadge({ status }) {
  const meta = STATUS_META[status] || STATUS_META.draft;
  return (
    <span
      className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-semibold ${meta.color} ${meta.bg} border ${meta.border}`}
    >
      <span className={`w-1.5 h-1.5 rounded-full ${meta.dot} flex-shrink-0`} />
      {meta.label}
    </span>
  );
}

// ─── New Post Modal ───────────────────────────────────────────────────────────

function NewPostModal({ onClose, onAdd, defaultDate }) {
  const [step, setStep] = useState(1);
  const [topic, setTopic] = useState("");
  const [platform, setPlatform] = useState("instagram");
  const [date, setDate] = useState(defaultDate || "2030-04-20");
  const [time, setTime] = useState("10:00 AM");
  const [status, setStatus] = useState("scheduled");
  const [generating, setGenerating] = useState(false);
  const [title, setTitle] = useState("");
  const [caption, setCaption] = useState("");
  const [category, setCategory] = useState("Productivity");
  const [img, setImg] = useState(IMG_POOL[0]);

  const handleGenerate = () => {
    if (!topic.trim()) return;
    setGenerating(true);
    setTimeout(() => {
      const t = topic.toLowerCase();
      if (
        t.includes("wellness") ||
        t.includes("health") ||
        t.includes("mind")
      ) {
        setTitle("Daily Mindfulness for Creators");
        setCategory("Wellness");
        setCaption(
          "Your mental health is your biggest asset. Unplug for 10 minutes every morning.\n#mindfulness #wellness #creators",
        );
        setImg(IMG_POOL[1]);
      } else if (
        t.includes("startup") ||
        t.includes("business") ||
        t.includes("scale")
      ) {
        setTitle("Scaling Systems Before You Need To");
        setCategory("Startup");
        setCaption(
          "Build systems before they're urgent. Automation isn't a shortcut — it's survival.\n#startup #founders #growth",
        );
        setImg(IMG_POOL[3]);
      } else if (
        t.includes("finance") ||
        t.includes("money") ||
        t.includes("invest")
      ) {
        setTitle("Compound Interest is the Cheat Code");
        setCategory("Lifestyle");
        setCaption(
          "Einstein called it the eighth wonder of the world. Start investing earlier than you think.\n#finance #wealth #investing",
        );
        setImg(IMG_POOL[2]);
      } else {
        setTitle("5 Micro Habits That Changed My Week");
        setCategory("Productivity");
        setCaption(
          "Small rituals, compounded daily, produce outsized results.\n#productivity #habits #focus",
        );
        setImg(IMG_POOL[0]);
      }
      setGenerating(false);
      setStep(2);
    }, 1300);
  };

  const handleAdd = () => {
    if (!title.trim()) return;
    onAdd({
      id: Date.now(),
      title,
      caption,
      category,
      dateString: date,
      time,
      platform,
      status,
      img,
      isAiAutopilot: false,
    });
    onClose();
  };

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-6 font-sans">
      <div className="bg-neutral-900 border border-neutral-800 rounded-3xl w-full max-w-lg overflow-hidden shadow-2xl shadow-black/50">
        <div className="flex items-center justify-between px-6 py-5 border-b border-neutral-800/60">
          <div>
            <h3 className="text-[14px] font-semibold text-white">
              Schedule a Post
            </h3>
            <p className="text-[11px] text-neutral-500 mt-0.5">
              {step === 1
                ? "Configure post details and let AI draft it."
                : "Review and confirm before scheduling."}
            </p>
          </div>
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1.5">
              <div
                className={`w-1.5 h-1.5 rounded-full transition-colors ${step >= 1 ? "bg-purple-500" : "bg-neutral-700"}`}
              />
              <div
                className={`w-1.5 h-1.5 rounded-full transition-colors ${step >= 2 ? "bg-purple-500" : "bg-neutral-700"}`}
              />
            </div>
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-xl flex items-center justify-center text-neutral-500 hover:text-white hover:bg-neutral-800 transition-all"
            >
              <FiX className="w-4 h-4" />
            </button>
          </div>
        </div>

        <div className="p-6 space-y-5 max-h-[70vh] overflow-y-auto">
          {step === 1 ? (
            <>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <label className="text-[9px] text-neutral-500 uppercase tracking-widest font-semibold block">
                    Platform
                  </label>
                  <select
                    value={platform}
                    onChange={(e) => setPlatform(e.target.value)}
                    className="w-full bg-neutral-950 border border-neutral-800 rounded-xl px-3 py-2.5 text-xs text-white focus:outline-none focus:border-purple-600 transition-colors"
                  >
                    <option value="instagram">Instagram</option>
                    <option value="linkedin">LinkedIn</option>
                    <option value="twitter">X (Twitter)</option>
                  </select>
                </div>
                <div className="space-y-1.5">
                  <label className="text-[9px] text-neutral-500 uppercase tracking-widest font-semibold block">
                    Status
                  </label>
                  <select
                    value={status}
                    onChange={(e) => setStatus(e.target.value)}
                    className="w-full bg-neutral-950 border border-neutral-800 rounded-xl px-3 py-2.5 text-xs text-white focus:outline-none focus:border-purple-600 transition-colors"
                  >
                    <option value="scheduled">Scheduled</option>
                    <option value="draft">Draft</option>
                  </select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <label className="text-[9px] text-neutral-500 uppercase tracking-widest font-semibold block">
                    Date
                  </label>
                  <input
                    type="date"
                    value={date}
                    onChange={(e) => setDate(e.target.value)}
                    className="w-full bg-neutral-950 border border-neutral-800 rounded-xl px-3 py-2.5 text-xs text-white focus:outline-none focus:border-purple-600 transition-colors"
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="text-[9px] text-neutral-500 uppercase tracking-widest font-semibold block">
                    Time
                  </label>
                  <input
                    type="text"
                    value={time}
                    onChange={(e) => setTime(e.target.value)}
                    placeholder="e.g. 10:00 AM"
                    className="w-full bg-neutral-950 border border-neutral-800 rounded-xl px-3 py-2.5 text-xs text-white focus:outline-none focus:border-purple-600 transition-colors"
                  />
                </div>
              </div>
              <div className="space-y-2">
                <label className="text-[9px] text-neutral-500 uppercase tracking-widest font-semibold block">
                  AI Content Seed
                </label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
                    placeholder="What's this post about?"
                    className="flex-1 bg-neutral-950 border border-neutral-800 rounded-xl px-3 py-2.5 text-xs text-white placeholder-neutral-600 focus:outline-none focus:border-purple-600 transition-colors"
                  />
                  <button
                    onClick={handleGenerate}
                    disabled={generating || !topic.trim()}
                    className="flex items-center gap-1.5 px-4 py-2.5 bg-purple-600 hover:bg-purple-500 disabled:bg-neutral-800 disabled:text-neutral-600 text-white text-xs font-semibold rounded-xl transition-all flex-shrink-0"
                  >
                    {generating ? (
                      <FiLoader className="w-3.5 h-3.5 animate-spin" />
                    ) : (
                      <FiZap className="w-3.5 h-3.5" />
                    )}
                    Generate
                  </button>
                </div>
                <div className="flex flex-wrap gap-1.5 pt-1">
                  {PROMPT_TOPICS.slice(0, 4).map((t) => (
                    <button
                      key={t}
                      onClick={() => setTopic(t)}
                      className="px-2.5 py-1 rounded-full bg-neutral-800 hover:bg-neutral-700 text-neutral-400 hover:text-neutral-200 text-[10px] font-medium transition-colors"
                    >
                      {t}
                    </button>
                  ))}
                </div>
              </div>
              <div className="pt-2 flex justify-end">
                <button
                  onClick={handleGenerate}
                  disabled={generating || !topic.trim()}
                  className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-fuchsia-600 to-purple-600 hover:from-fuchsia-500 hover:to-purple-500 disabled:from-neutral-800 disabled:to-neutral-800 disabled:text-neutral-600 text-white text-xs font-semibold rounded-full transition-all"
                >
                  {generating ? (
                    <>
                      <FiLoader className="w-3.5 h-3.5 animate-spin" />{" "}
                      Generating…
                    </>
                  ) : (
                    <>
                      <FiZap className="w-3.5 h-3.5" /> Generate & Preview
                    </>
                  )}
                </button>
              </div>
            </>
          ) : (
            <>
              <div className="bg-neutral-950 border border-neutral-800/80 rounded-2xl overflow-hidden">
                <img src={img} alt="" className="w-full h-48 object-cover" />
                <div className="p-4 space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-[9px] text-neutral-500 uppercase tracking-widest font-bold">
                      {category}
                    </span>
                    <div className="flex items-center gap-1.5">
                      <PlatformBadge platform={platform} />
                      <StatusBadge status={status} />
                    </div>
                  </div>
                  <input
                    type="text"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    className="bg-transparent text-[14px] font-bold text-white w-full border-b border-neutral-800 focus:outline-none focus:border-purple-500 pb-1 transition-colors"
                  />
                  <textarea
                    value={caption}
                    onChange={(e) => setCaption(e.target.value)}
                    rows={4}
                    className="bg-transparent text-[11px] text-neutral-400 w-full border border-neutral-800/80 rounded-xl p-3 focus:outline-none focus:border-purple-500 leading-relaxed font-sans resize-none transition-colors"
                  />
                  <div className="flex items-center gap-3 text-[10px] text-neutral-600">
                    <span className="flex items-center gap-1">
                      <FiCalendar className="w-3 h-3" />
                      {date}
                    </span>
                    <span className="flex items-center gap-1">
                      <FiClock className="w-3 h-3" />
                      {time}
                    </span>
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <button
                  onClick={() => setStep(1)}
                  className="flex-1 py-2.5 px-4 bg-neutral-800 hover:bg-neutral-700 text-neutral-300 hover:text-white text-xs font-semibold rounded-xl transition-all"
                >
                  Back & Edit
                </button>
                <button
                  onClick={handleAdd}
                  className="flex-1 py-2.5 px-4 bg-gradient-to-r from-fuchsia-600 to-purple-600 hover:from-fuchsia-500 hover:to-purple-500 text-white text-xs font-semibold rounded-xl transition-all flex items-center justify-center gap-2"
                >
                  <FiSend className="w-3.5 h-3.5" /> Add to Schedule
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// ─── Post Detail Modal ────────────────────────────────────────────────────────

function PostDetailModal({ post, onClose, onDelete }) {
  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-6 font-sans">
      <div className="bg-neutral-900 border border-neutral-800 rounded-3xl w-full max-w-sm overflow-hidden shadow-2xl shadow-black/50">
        <div className="relative">
          <img src={post.img} alt="" className="w-full h-52 object-cover" />
          <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />
          <button
            onClick={onClose}
            className="absolute top-3 right-3 w-8 h-8 rounded-xl bg-black/50 backdrop-blur-sm flex items-center justify-center text-white hover:bg-black/70 transition-all"
          >
            <FiX className="w-4 h-4" />
          </button>
          <div className="absolute bottom-3 left-4 right-4">
            <span className="text-[9px] font-bold text-neutral-400 uppercase tracking-widest block">
              {post.category}
            </span>
            <h3 className="text-sm font-bold text-white mt-0.5 leading-snug">
              {post.title}
            </h3>
          </div>
        </div>
        <div className="p-5 space-y-4">
          <div className="flex items-center gap-2 flex-wrap">
            <PlatformBadge platform={post.platform} />
            <StatusBadge status={post.status} />
            {post.isAiAutopilot && (
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold text-purple-400 bg-purple-500/10 border border-purple-500/20">
                <FiZap className="w-2.5 h-2.5" /> AI Autopilot
              </span>
            )}
          </div>
          <div className="bg-neutral-950/70 border border-neutral-800/60 rounded-2xl p-4">
            <p className="text-[9px] font-bold text-neutral-600 uppercase tracking-widest mb-2">
              Caption
            </p>
            <p className="text-[11px] text-neutral-300 leading-relaxed whitespace-pre-wrap font-sans">
              {post.caption}
            </p>
          </div>
          <div className="flex items-center justify-between text-[11px] text-neutral-500">
            <span className="flex items-center gap-1.5">
              <FiCalendar className="w-3.5 h-3.5" />
              {post.dateString}
            </span>
            <span className="flex items-center gap-1.5">
              <FiClock className="w-3.5 h-3.5" />
              {post.time}
            </span>
          </div>
          <div className="flex gap-2.5 pt-1">
            <button
              onClick={() => {
                onDelete(post.id);
                onClose();
              }}
              className="flex-1 py-2.5 px-3 bg-red-500/10 border border-red-500/20 hover:bg-red-500/20 text-red-400 rounded-xl text-xs font-semibold transition-all flex items-center justify-center gap-1.5"
            >
              <FiTrash2 className="w-3.5 h-3.5" /> Delete
            </button>
            <button
              onClick={onClose}
              className="flex-1 py-2.5 px-3 bg-neutral-800 hover:bg-neutral-700 text-neutral-300 hover:text-white rounded-xl text-xs font-semibold transition-all"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Queue Sidebar ────────────────────────────────────────────────────────────

function QueueSidebar({
  posts,
  selectedDate,
  onReorder,
  onSelect,
  onDelete,
  filterStatus,
  setFilterStatus,
}) {
  const [queueView, setQueueView] = useState("list"); // "list" | "grid"
  const [draggingId, setDraggingId] = useState(null);
  const [dragOverId, setDragOverId] = useState(null);
  const dragItem = useRef(null);
  const dragOverItem = useRef(null);

  const dayPosts = selectedDate
    ? posts.filter((p) => p.dateString === selectedDate)
    : posts.filter(
        (p) => p.dateString === posts.map((x) => x.dateString).sort()[0],
      );

  const filteredQueue =
    filterStatus === "all"
      ? dayPosts
      : dayPosts.filter((p) => p.status === filterStatus);

  // Sort by time within the day
  const sortedQueue = [...filteredQueue].sort((a, b) => {
    const toMin = (t) => {
      const [time, period] = t.split(" ");
      let [h, m] = time.split(":").map(Number);
      if (period === "PM" && h !== 12) h += 12;
      if (period === "AM" && h === 12) h = 0;
      return h * 60 + m;
    };
    return toMin(a.time) - toMin(b.time);
  });

  const handleDragStart = (e, id, idx) => {
    setDraggingId(id);
    dragItem.current = idx;
    e.dataTransfer.effectAllowed = "move";
  };

  const handleDragEnter = (e, id, idx) => {
    setDragOverId(id);
    dragOverItem.current = idx;
  };

  const handleDragEnd = () => {
    if (
      dragItem.current !== null &&
      dragOverItem.current !== null &&
      dragItem.current !== dragOverItem.current
    ) {
      // Reorder within the full posts array preserving other days
      const dayPostIds = sortedQueue.map((p) => p.id);
      const reordered = [...dayPostIds];
      const [moved] = reordered.splice(dragItem.current, 1);
      reordered.splice(dragOverItem.current, 0, moved);
      onReorder(reordered, selectedDate);
    }
    setDraggingId(null);
    setDragOverId(null);
    dragItem.current = null;
    dragOverItem.current = null;
  };

  const displayDate = selectedDate
    ? new Date(selectedDate + "T00:00:00").toLocaleDateString("en-US", {
        weekday: "long",
        month: "long",
        day: "numeric",
      })
    : "Select a date";

  return (
    <div className="w-[300px] flex-shrink-0 bg-neutral-950 border-l border-neutral-800/60 flex flex-col h-full overflow-hidden">
      {/* Queue Header */}
      <div className="px-5 pt-6 pb-4 border-b border-neutral-800/60 flex-shrink-0">
        <div className="flex items-center justify-between mb-1">
          <h3 className="text-[14px] font-semibold text-white">Queue</h3>
          <div className="flex items-center gap-1 bg-neutral-900 rounded-full p-0.5 border border-neutral-800/40">
            <button
              onClick={() => setQueueView("list")}
              title="List view"
              className={`w-7 h-7 rounded-full flex items-center justify-center transition-all ${queueView === "list" ? "bg-neutral-800 text-white" : "text-neutral-500 hover:text-neutral-300"}`}
            >
              <FiList className="w-3.5 h-3.5" />
            </button>
            <button
              onClick={() => setQueueView("grid")}
              title="Grid view"
              className={`w-7 h-7 rounded-full flex items-center justify-center transition-all ${queueView === "grid" ? "bg-neutral-800 text-white" : "text-neutral-500 hover:text-neutral-300"}`}
            >
              <FiGrid className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
        <p className="text-[11px] text-neutral-500">{displayDate}</p>
        <p className="text-[10px] text-neutral-600 mt-0.5">
          {sortedQueue.length} post{sortedQueue.length !== 1 ? "s" : ""} · drag
          to reorder
        </p>
      </div>

      {/* Status filter capsules */}
      <div className="px-5 py-3 border-b border-neutral-800/40 flex-shrink-0">
        <div className="flex items-center gap-1.5 flex-wrap">
          {["all", "scheduled", "published", "draft", "autopilot"].map((s) => {
            const meta = STATUS_META[s];
            const isActive = filterStatus === s;
            const activeClass = isActive
              ? s === "all"
                ? "bg-neutral-800 text-white border-neutral-700"
                : `${meta.bg} ${meta.color} ${meta.border}`
              : "text-neutral-500 border-neutral-800/40 hover:text-neutral-300 hover:border-neutral-700";
            return (
              <button
                key={s}
                onClick={() => setFilterStatus(s)}
                className={`px-2.5 py-1 rounded-full text-[10px] font-semibold transition-all border ${activeClass}`}
              >
                {s === "all" ? "All" : s.charAt(0).toUpperCase() + s.slice(1)}
              </button>
            );
          })}
        </div>
      </div>

      {/* Queue Items */}
      <div className="flex-1 overflow-y-auto px-3 py-3 space-y-2 [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
        {sortedQueue.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-40 text-center px-4">
            <FiCalendar className="w-8 h-8 text-neutral-700 mb-3" />
            <p className="text-[12px] font-semibold text-neutral-500">
              Nothing queued
            </p>
            <p className="text-[11px] text-neutral-700 mt-1">
              Select a date with posts or schedule a new one.
            </p>
          </div>
        ) : queueView === "list" ? (
          sortedQueue.map((post, idx) => {
            const isDragging = draggingId === post.id;
            const isOver = dragOverId === post.id;
            return (
              <div
                key={post.id}
                draggable
                onDragStart={(e) => handleDragStart(e, post.id, idx)}
                onDragEnter={(e) => handleDragEnter(e, post.id, idx)}
                onDragEnd={handleDragEnd}
                onDragOver={(e) => e.preventDefault()}
                onClick={() => onSelect(post)}
                className={`group relative flex items-center gap-3 p-3 rounded-xl border cursor-pointer transition-all duration-200 ${
                  isDragging
                    ? "opacity-40 scale-95 border-purple-500/40 bg-purple-500/5"
                    : isOver
                      ? "border-purple-500/50 bg-purple-500/5 scale-[1.01]"
                      : "border-neutral-800/50 bg-neutral-900/60 hover:border-neutral-700 hover:bg-neutral-900"
                }`}
              >
                {/* Drag handle */}
                <div className="flex flex-col gap-0.5 flex-shrink-0 cursor-grab active:cursor-grabbing opacity-30 group-hover:opacity-70 transition-opacity">
                  <div className="w-3 h-0.5 bg-neutral-400 rounded-full" />
                  <div className="w-3 h-0.5 bg-neutral-400 rounded-full" />
                  <div className="w-3 h-0.5 bg-neutral-400 rounded-full" />
                </div>

                {/* Queue position */}
                <span className="text-[10px] font-bold text-neutral-700 w-3 flex-shrink-0 text-center">
                  {idx + 1}
                </span>

                <img
                  src={post.img}
                  alt=""
                  className="w-10 h-10 rounded-lg object-cover flex-shrink-0"
                />

                <div className="flex-1 min-w-0">
                  <p className="text-[12px] font-semibold text-neutral-200 truncate group-hover:text-white transition-colors leading-tight">
                    {post.title}
                  </p>
                  <div className="flex items-center gap-2 mt-1">
                    <StatusBadge status={post.status} />
                  </div>
                  <div className="flex items-center gap-1 mt-1 text-[9px] text-neutral-600">
                    <FiClock className="w-2.5 h-2.5" />
                    <span>{post.time}</span>
                    <span className="text-neutral-700 mx-0.5">·</span>
                    <span className="w-3 h-3 flex items-center justify-center">
                      {PLATFORM_META[post.platform]?.icon}
                    </span>
                  </div>
                </div>

                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    onDelete(post.id);
                  }}
                  className="opacity-0 group-hover:opacity-100 w-6 h-6 rounded-lg flex items-center justify-center text-neutral-600 hover:text-red-400 hover:bg-red-500/10 transition-all flex-shrink-0"
                >
                  <FiTrash2 className="w-3 h-3" />
                </button>
              </div>
            );
          })
        ) : (
          // Grid view
          <div className="grid grid-cols-2 gap-2">
            {sortedQueue.map((post, idx) => {
              const isDragging = draggingId === post.id;
              const isOver = dragOverId === post.id;
              return (
                <div
                  key={post.id}
                  draggable
                  onDragStart={(e) => handleDragStart(e, post.id, idx)}
                  onDragEnter={(e) => handleDragEnter(e, post.id, idx)}
                  onDragEnd={handleDragEnd}
                  onDragOver={(e) => e.preventDefault()}
                  onClick={() => onSelect(post)}
                  className={`group relative rounded-xl border overflow-hidden cursor-pointer transition-all duration-200 ${
                    isDragging
                      ? "opacity-40 scale-95 border-purple-500/40"
                      : isOver
                        ? "border-purple-500/50 scale-[1.02]"
                        : "border-neutral-800/50 hover:border-neutral-700"
                  }`}
                >
                  <div className="relative aspect-square bg-neutral-800">
                    <img
                      src={post.img}
                      alt=""
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent" />
                    <span className="absolute top-1.5 left-1.5 w-4 h-4 rounded-full bg-black/60 flex items-center justify-center text-[8px] font-bold text-neutral-300">
                      {idx + 1}
                    </span>
                    {post.isAiAutopilot && (
                      <span className="absolute top-1.5 right-1.5 w-4 h-4 rounded-full bg-purple-600/90 flex items-center justify-center">
                        <FiZap className="w-2 h-2 text-white" />
                      </span>
                    )}
                    <div className="absolute bottom-1.5 left-1.5 right-1.5">
                      <p className="text-[9px] font-semibold text-white leading-tight truncate">
                        {post.title}
                      </p>
                      <p className="text-[8px] text-neutral-400 mt-0.5">
                        {post.time}
                      </p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Calendar Views ───────────────────────────────────────────────────────────

function MonthView({
  posts,
  currentDate,
  selectedDate,
  onSelectDate,
  onSelectPost,
}) {
  const getDays = () => {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();
    const firstDay = new Date(year, month, 1).getDay();
    const totalDays = new Date(year, month + 1, 0).getDate();
    const prevTotal = new Date(year, month, 0).getDate();
    const days = [];
    for (let i = firstDay - 1; i >= 0; i--)
      days.push({ day: prevTotal - i, curr: false });
    for (let d = 1; d <= totalDays; d++) days.push({ day: d, curr: true });
    while (days.length < 42)
      days.push({ day: days.length - firstDay - totalDays + 1, curr: false });
    return days;
  };

  const formatDs = (day) => {
    const y = currentDate.getFullYear();
    const m = String(currentDate.getMonth() + 1).padStart(2, "0");
    return `${y}-${m}-${String(day).padStart(2, "0")}`;
  };

  const days = getDays();

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      {/* Day header row */}
      <div className="grid grid-cols-7 border-b border-neutral-800/60 flex-shrink-0">
        {DAY_LABELS_SHORT.map((d) => (
          <div
            key={d}
            className="py-3 text-center text-[10px] font-bold text-neutral-600 uppercase tracking-widest"
          >
            {d}
          </div>
        ))}
      </div>

      {/* Day cells */}
      <div
        className="grid grid-cols-7 flex-1"
        style={{ gridTemplateRows: "repeat(6, minmax(0, 1fr))" }}
      >
        {days.map((item, idx) => {
          const ds = item.curr ? formatDs(item.day) : null;
          const dayPosts = ds ? posts.filter((p) => p.dateString === ds) : [];
          const isSelected = ds && selectedDate === ds;
          const isToday =
            item.curr && item.day === 4 && currentDate.getMonth() === 3;

          return (
            <div
              key={idx}
              onClick={() => ds && onSelectDate(isSelected ? null : ds)}
              className={`border-b border-r border-neutral-800/30 p-2 flex flex-col transition-colors duration-150 ${
                (idx + 1) % 7 === 0 ? "border-r-0" : ""
              } ${idx >= 35 ? "border-b-0" : ""} ${
                !item.curr
                  ? "bg-neutral-950/60"
                  : isSelected
                    ? "bg-purple-500/5 border-purple-500/20 cursor-pointer"
                    : "cursor-pointer hover:bg-neutral-900/40"
              }`}
            >
              <span
                className={`text-[11px] font-semibold w-6 h-6 flex items-center justify-center rounded-full mb-1 flex-shrink-0 ${
                  isToday
                    ? "bg-blue-600 text-white"
                    : isSelected
                      ? "bg-purple-600 text-white"
                      : item.curr
                        ? "text-neutral-400"
                        : "text-neutral-700"
                }`}
              >
                {item.day}
              </span>

              <div className="space-y-0.5 overflow-hidden flex-1">
                {dayPosts.slice(0, 3).map((post) => {
                  const meta = STATUS_META[post.status] || STATUS_META.draft;
                  const platMeta =
                    PLATFORM_META[post.platform] || PLATFORM_META.instagram;
                  return (
                    <button
                      key={post.id}
                      onClick={(e) => {
                        e.stopPropagation();
                        onSelectPost(post);
                      }}
                      className={`w-full text-left px-1.5 py-0.5 rounded-md text-[9px] font-semibold truncate flex items-center gap-1 transition-all hover:opacity-80 ${meta.color} ${meta.bg}`}
                    >
                      <span className="w-2.5 h-2.5 flex-shrink-0">
                        {platMeta.icon}
                      </span>
                      <span className="truncate">{post.title}</span>
                    </button>
                  );
                })}
                {dayPosts.length > 3 && (
                  <p className="text-[9px] text-neutral-600 pl-1">
                    +{dayPosts.length - 3} more
                  </p>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function WeekView({
  posts,
  currentDate,
  selectedDate,
  onSelectDate,
  onSelectPost,
}) {
  const getWeekDays = () => {
    const day = currentDate.getDay();
    const startOfWeek = new Date(currentDate);
    startOfWeek.setDate(currentDate.getDate() - day);
    return Array.from({ length: 7 }, (_, i) => {
      const d = new Date(startOfWeek);
      d.setDate(startOfWeek.getDate() + i);
      return d;
    });
  };

  const weekDays = getWeekDays();
  const formatDs = (d) =>
    `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
  const hours = Array.from({ length: 14 }, (_, i) => i + 7); // 7 AM → 8 PM

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      {/* Week day headers */}
      <div
        className="grid border-b border-neutral-800/60 flex-shrink-0"
        style={{ gridTemplateColumns: "56px repeat(7, 1fr)" }}
      >
        <div className="py-3" />
        {weekDays.map((d, i) => {
          const ds = formatDs(d);
          const isSelected = selectedDate === ds;
          const isToday = d.getDate() === 4 && d.getMonth() === 3;
          return (
            <div
              key={i}
              onClick={() => onSelectDate(isSelected ? null : ds)}
              className="py-3 text-center cursor-pointer hover:bg-neutral-900/40 transition-colors"
            >
              <p className="text-[10px] font-bold text-neutral-600 uppercase tracking-widest">
                {DAY_LABELS_SHORT[i]}
              </p>
              <span
                className={`text-[13px] font-semibold w-7 h-7 flex items-center justify-center rounded-full mx-auto mt-1 ${
                  isSelected
                    ? "bg-purple-600 text-white"
                    : isToday
                      ? "bg-blue-600 text-white"
                      : "text-neutral-400"
                }`}
              >
                {d.getDate()}
              </span>
            </div>
          );
        })}
      </div>

      {/* Hour grid */}
      <div className="flex-1 overflow-y-auto">
        {hours.map((hour) => (
          <div
            key={hour}
            className="grid border-b border-neutral-800/20"
            style={{
              gridTemplateColumns: "56px repeat(7, 1fr)",
              minHeight: "60px",
            }}
          >
            <div className="flex items-start justify-end pr-3 pt-1">
              <span className="text-[9px] text-neutral-700 font-medium">
                {hour === 12
                  ? "12 PM"
                  : hour < 12
                    ? `${hour} AM`
                    : `${hour - 12} PM`}
              </span>
            </div>
            {weekDays.map((d, di) => {
              const ds = formatDs(d);
              const isSelected = selectedDate === ds;
              const slotPosts = posts.filter((p) => {
                if (p.dateString !== ds) return false;
                const [t, period] = p.time.split(" ");
                let [h] = t.split(":").map(Number);
                if (period === "PM" && h !== 12) h += 12;
                if (period === "AM" && h === 12) h = 0;
                return h === hour;
              });
              return (
                <div
                  key={di}
                  onClick={() => onSelectDate(isSelected ? null : ds)}
                  className={`border-l border-neutral-800/30 p-1 transition-colors cursor-pointer ${isSelected ? "bg-purple-500/5" : "hover:bg-neutral-900/30"}`}
                >
                  {slotPosts.map((post) => {
                    const meta = STATUS_META[post.status] || STATUS_META.draft;
                    return (
                      <button
                        key={post.id}
                        onClick={(e) => {
                          e.stopPropagation();
                          onSelectPost(post);
                        }}
                        className={`w-full text-left px-2 py-1 rounded-lg text-[9px] font-semibold mb-0.5 truncate ${meta.color} ${meta.bg} border ${meta.border} transition-opacity hover:opacity-80`}
                      >
                        {post.title}
                      </button>
                    );
                  })}
                </div>
              );
            })}
          </div>
        ))}
      </div>
    </div>
  );
}

function DayView({
  posts,
  currentDate,
  selectedDate,
  onSelectDate,
  onSelectPost,
}) {
  const formatDs = (d) =>
    `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
  const ds = formatDs(currentDate);
  const dayPosts = posts
    .filter((p) => p.dateString === ds)
    .sort((a, b) => {
      const toMin = (t) => {
        const [time, period] = t.split(" ");
        let [h, m] = time.split(":").map(Number);
        if (period === "PM" && h !== 12) h += 12;
        if (period === "AM" && h === 12) h = 0;
        return h * 60 + m;
      };
      return toMin(a.time) - toMin(b.time);
    });
  const hours = Array.from({ length: 14 }, (_, i) => i + 7);

  useEffect(() => {
    onSelectDate(ds);
  }, [ds]);

  return (
    <div className="flex-1 overflow-y-auto">
      <div className="px-8 py-6">
        <p className="text-[12px] text-neutral-500 mb-6">
          {currentDate.toLocaleDateString("en-US", {
            weekday: "long",
            month: "long",
            day: "numeric",
            year: "numeric",
          })}
          <span className="ml-2 text-neutral-700">·</span>
          <span className="ml-2 text-neutral-600">
            {dayPosts.length} post{dayPosts.length !== 1 ? "s" : ""} scheduled
          </span>
        </p>
        <div className="space-y-0">
          {hours.map((hour) => {
            const slotPosts = dayPosts.filter((p) => {
              const [t, period] = p.time.split(" ");
              let [h] = t.split(":").map(Number);
              if (period === "PM" && h !== 12) h += 12;
              if (period === "AM" && h === 12) h = 0;
              return h === hour;
            });
            return (
              <div
                key={hour}
                className="flex gap-6 border-b border-neutral-800/30 py-3 min-h-[52px]"
              >
                <span className="text-[10px] text-neutral-700 font-medium w-12 flex-shrink-0 pt-0.5 text-right">
                  {hour === 12
                    ? "12 PM"
                    : hour < 12
                      ? `${hour} AM`
                      : `${hour - 12} PM`}
                </span>
                <div className="flex-1 space-y-2">
                  {slotPosts.map((post) => {
                    const meta = STATUS_META[post.status] || STATUS_META.draft;
                    const platMeta =
                      PLATFORM_META[post.platform] || PLATFORM_META.instagram;
                    return (
                      <button
                        key={post.id}
                        onClick={() => onSelectPost(post)}
                        className={`w-full text-left flex items-center gap-3 px-4 py-3 rounded-xl border ${meta.bg} ${meta.border} hover:opacity-80 transition-all group`}
                      >
                        <img
                          src={post.img}
                          alt=""
                          className="w-10 h-10 rounded-lg object-cover flex-shrink-0"
                        />
                        <div className="flex-1 min-w-0">
                          <p
                            className={`text-[12px] font-semibold ${meta.color} truncate`}
                          >
                            {post.title}
                          </p>
                          <p className="text-[10px] text-neutral-500 truncate mt-0.5">
                            {post.caption.split("\n")[0]}
                          </p>
                        </div>
                        <div className="flex items-center gap-2 flex-shrink-0">
                          <span className="w-4 h-4 flex items-center justify-center">
                            {platMeta.icon}
                          </span>
                          <StatusBadge status={post.status} />
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

// ─── Main Schedule Page ───────────────────────────────────────────────────────

export default function Schedule({ setActiveView, isSyncing, syncData }) {
  const [posts, setPosts] = useState(() => {
    const saved = localStorage.getItem("growthos_scheduled_posts");
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch {
        return SEED_POSTS;
      }
    }
    return SEED_POSTS;
  });

  const [calView, setCalView] = useState("month"); // "month" | "week" | "day"
  const [currentDate, setCurrentDate] = useState(new Date("2030-04-01"));
  const [selectedDate, setSelectedDate] = useState(null);
  const [selectedPost, setSelectedPost] = useState(null);
  const [isNewPostOpen, setIsNewPostOpen] = useState(false);
  const [filterStatus, setFilterStatus] = useState("all");
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    localStorage.setItem("growthos_scheduled_posts", JSON.stringify(posts));
  }, [posts]);

  const handleDelete = (id) =>
    setPosts((prev) => prev.filter((p) => p.id !== id));
  const handleAdd = (post) => setPosts((prev) => [...prev, post]);

  const handleReorder = (orderedIds, dateString) => {
    setPosts((prev) => {
      const otherPosts = prev.filter((p) => p.dateString !== dateString);
      const reordered = orderedIds
        .map((id) => prev.find((p) => p.id === id))
        .filter(Boolean);
      return [...otherPosts, ...reordered];
    });
  };

  const navigatePrev = () => {
    if (calView === "month")
      setCurrentDate(
        new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1),
      );
    else if (calView === "week") {
      const d = new Date(currentDate);
      d.setDate(d.getDate() - 7);
      setCurrentDate(d);
    } else {
      const d = new Date(currentDate);
      d.setDate(d.getDate() - 1);
      setCurrentDate(d);
    }
  };

  const navigateNext = () => {
    if (calView === "month")
      setCurrentDate(
        new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1),
      );
    else if (calView === "week") {
      const d = new Date(currentDate);
      d.setDate(d.getDate() + 7);
      setCurrentDate(d);
    } else {
      const d = new Date(currentDate);
      d.setDate(d.getDate() + 1);
      setCurrentDate(d);
    }
  };

  const navLabel = () => {
    if (calView === "month")
      return `${MONTH_NAMES[currentDate.getMonth()]} ${currentDate.getFullYear()}`;
    if (calView === "week") {
      const day = currentDate.getDay();
      const start = new Date(currentDate);
      start.setDate(currentDate.getDate() - day);
      const end = new Date(start);
      end.setDate(start.getDate() + 6);
      return `${start.toLocaleDateString("en-US", { month: "short", day: "numeric" })} – ${end.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`;
    }
    return currentDate.toLocaleDateString("en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
      year: "numeric",
    });
  };

  return (
    <div className="flex-1 bg-neutral-950 text-neutral-200 font-sans flex flex-col h-full overflow-hidden">
      {/* ── Header — matches Dashboard exactly ── */}
      <header
        className="w-full px-8 pt-6 pb-6 flex items-center border-b border-neutral-800 justify-between z-30 flex-shrink-0 transition-all duration-300"
        style={{ background: "rgba(9,9,9,0.8)", backdropFilter: "blur(20px)" }}
      >
        <div>
          <h2 className="text-[18px] font-semibold text-white tracking-tight">
            Schedule
          </h2>
          <p className="text-[14px] text-neutral-500 mt-0.5">
            Plan and manage your content pipeline.
          </p>
        </div>

        <div className="flex items-center gap-3">
          {/* Search */}
          <div className="relative">
            <FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-neutral-300" />
            <input
              type="text"
              placeholder="Search now"
              className="bg-neutral-900 text-[12px] text-neutral-300 placeholder-neutral-400 rounded-full pl-8 pr-4 py-2.5 w-48 focus:outline-none transition-all"
            />
          </div>

          {/* Sync */}
          <button
            onClick={syncData}
            disabled={isSyncing}
            title="Sync workspace data"
            className="flex items-center gap-1.5 px-5 py-2.5 rounded-full bg-neutral-800 hover:bg-neutral-700 text-neutral-400 hover:text-white text-[12px] font-medium transition-colors disabled:opacity-50"
          >
            {isSyncing ? (
              <FiLoader className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <FiRefreshCw className="w-3.5 h-3.5" />
            )}
            <span>{isSyncing ? "Syncing…" : "Sync"}</span>
          </button>
        </div>
      </header>

      {/* ── Calendar toolbar ── */}
      <div className="flex items-center justify-between px-8 py-4 border-b border-neutral-800/60 flex-shrink-0 bg-neutral-950/80">
        {/* Nav arrows + label */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1">
            <button
              onClick={navigatePrev}
              className="w-8 h-8 rounded-lg flex items-center justify-center text-neutral-500 hover:text-neutral-200 hover:bg-neutral-800 transition-colors"
            >
              <FiChevronLeft className="w-4 h-4" />
            </button>
            <button
              onClick={navigateNext}
              className="w-8 h-8 rounded-lg flex items-center justify-center text-neutral-500 hover:text-neutral-200 hover:bg-neutral-800 transition-colors"
            >
              <FiChevronRight className="w-4 h-4" />
            </button>
          </div>
          <h3 className="text-[15px] font-semibold text-white min-w-[220px]">
            {navLabel()}
          </h3>
        </div>

        {/* Right: view toggle capsules + New Post */}
        <div className="flex items-center gap-3">
          {/* Monthly / Weekly / Daily capsule filter */}
          <div className="flex items-center gap-1.5 bg-neutral-900 rounded-full p-1 border border-neutral-800/40">
            {[
              { id: "month", label: "Monthly" },
              { id: "week", label: "Weekly" },
              { id: "day", label: "Daily" },
            ].map((v) => (
              <button
                key={v.id}
                onClick={() => setCalView(v.id)}
                className={`px-4 py-1.5 rounded-full text-[12px] font-semibold transition-all ${
                  calView === v.id
                    ? "bg-neutral-800 text-white"
                    : "text-neutral-500 hover:text-neutral-300"
                }`}
              >
                {v.label}
              </button>
            ))}
          </div>

          {/* New Post */}
          <button
            onClick={() => setIsNewPostOpen(true)}
            className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-fuchsia-600 to-purple-600 hover:from-fuchsia-500 hover:to-purple-500 text-white text-[12px] font-semibold rounded-full transition-all hover:scale-[1.02] active:scale-[0.98] shadow-lg shadow-purple-950/40"
          >
            <FiPlus className="w-3.5 h-3.5" />
            New Post
          </button>
        </div>
      </div>

      {/* ── Body: Calendar + Queue Sidebar ── */}
      <div className="flex flex-1 overflow-hidden">
        {/* Calendar area */}
        <div className="flex-1 flex flex-col overflow-hidden">
          {calView === "month" && (
            <MonthView
              posts={posts}
              currentDate={currentDate}
              selectedDate={selectedDate}
              onSelectDate={setSelectedDate}
              onSelectPost={setSelectedPost}
            />
          )}
          {calView === "week" && (
            <WeekView
              posts={posts}
              currentDate={currentDate}
              selectedDate={selectedDate}
              onSelectDate={setSelectedDate}
              onSelectPost={setSelectedPost}
            />
          )}
          {calView === "day" && (
            <DayView
              posts={posts}
              currentDate={currentDate}
              selectedDate={selectedDate}
              onSelectDate={setSelectedDate}
              onSelectPost={setSelectedPost}
            />
          )}
        </div>

        {/* Queue sidebar */}
        <QueueSidebar
          posts={posts}
          selectedDate={selectedDate}
          onReorder={handleReorder}
          onSelect={setSelectedPost}
          onDelete={handleDelete}
          filterStatus={filterStatus}
          setFilterStatus={setFilterStatus}
        />
      </div>

      {/* ── Modals ── */}
      {isNewPostOpen && (
        <NewPostModal
          onClose={() => setIsNewPostOpen(false)}
          onAdd={handleAdd}
          defaultDate={selectedDate}
        />
      )}
      {selectedPost && (
        <PostDetailModal
          post={selectedPost}
          onClose={() => setSelectedPost(null)}
          onDelete={handleDelete}
        />
      )}
    </div>
  );
}
